function initialiseSavedReposListing() {
  let urlContainer = document.getElementById("url-container");
  let savedReposContainer = document.getElementById("saved-repos");

  // No saved repos
  if (urlContainer.innerHTML == "") {
    savedReposContainer.innerHTML += `
      <div class="container">
        <h2>No saved repos</h2>
      </div>
    `;
    return;
  }

  // Found saved repos to retrieve, make requests for each one
  let urls = urlContainer.innerHTML.split("²");
  // array used to determine when the last xhr finished to be able to get the
  // elements that were generated by their results
  var donexhrs = 0;
  // -1 because I'm adding a separator at the end of everything in the php
  // template file which makes the urls longer by one
  for (let index = 0; index < urls.length - 1; index++) {
    splitUrl = urls[index].split("ⁿ");
    let url = {};
    url.id = splitUrl[0];
    url.link = splitUrl[1];
    let xhr = new XMLHttpRequest();
    xhr.open("GET", url.link, true);
    xhr.onload = () => {
      if (xhr.status == 200) {
        // Parse and display repo
        let repo = JSON.parse(xhr.responseText);
        savedReposContainer.innerHTML += `
        <div class="container repo-container">
          <input type="hidden" id="repo-id-` + index + `" value="` + url.id + `">
          <div class="repo-part">
            <a href="` + repo.html_url + `" target="_blank" class="repo-link">
              <h3 class="repo-title">` + repo.name + `</h3>
            </a>`
          + repo.description + `
          </div>
          <div class="repo-part">
            <span class="repo-stat">Forks: ` + repo.forks_count + `</span>
            <span class="repo-stat">Watchers: ` + repo.watchers_count + `</span>
            <span class="repo-stat">Stars: ` + repo.stargazers_count + `</span>
          </div>
          <button id="repo-delete-button-` + index + `" class="repo-delete-button" type="button">Unsave repo</button>
        </div>
        `;
        ++donexhrs;
        // -1 because I'm adding a separator at the end of everything in the php
        // template file which makes the urls longer by one
        if (donexhrs != urls.length - 1) {
          return;
        }
        // Otherwise continue by initialising all the buttons, since all of the
        // requests have finished
        for (let index = 0; index < urls.length - 1; index++) {
          // Initialise button that saves each repo for current user
          let deleteRepoButton = document.getElementById("repo-delete-button-" + index);
          let dbRepoId = document.getElementById("repo-id-" + index).value;
          deleteRepoButton.addEventListener("click", function () {
            let xhrSaveRepo = new XMLHttpRequest();
            xhrSaveRepo.open("GET", "logic/delete-repo.php?repo_id=" + dbRepoId);
            xhrSaveRepo.onload = function () {
              if (xhrSaveRepo.status == 200) {
                deleteRepoButton.innerHTML = "Done";
                deleteRepoButton.onclick = null;
              }
              else if (xhrSaveRepo.status == 470) {
                deleteRepoButton.innerHTML = "Could not unsave this repo: the id was not sent properly, please contact website administrator.";
                saveRepoButton.onclick = null;
              }
            }
            xhrSaveRepo.send();
          });
        }
        urlContainer.remove();
      }
    };
    xhr.send();
  }
}
